### PR TITLE
Reorganizing the files for the expanded course structure.

### PR DESCRIPTION
**Pull request by yuri**
This is just renaming files to allow for the expanded structure and splitting the oversized "services" module into 4 different ones.

@SethDavenport Can you review for a sanity check?

### CODE REVIEW

**Comment by SethDavenport** [comment]
Looks reasonable.  Can you clarify what sections 0 to 3 are?  In my mind I have:

0 - Setup
1 - Toolchain (the one I did yesterday)
2 - JS for Angular
3 - ?
4 - 16 ... as in this PR.

**Comment by SethDavenport** [comment]
I'm thinking of doing a custom validation example in the forms section (11 in the new scheme).  However, such an example would involve creating a directive.  Does it make sense to switch the ordering of sections 11 and 12?

**Comment by yuri** [comment]
@SethDavenport Part 2 is "Introduction to AngularJS" (a high level intro, what was earlier done with slides). Part 3 is what "JavaScript for AngularJS Developers".

**Comment by yuri** [comment]
@SethDavenport Yes, we can swap 11 and 12.

**Pull request merged**
