### PR TITLE
Unit testing controllers and directives

### PR DESCRIPTION
**Pull request by SethDavenport**
Examples for a controller and a directive with an inline template.  Still working on an example for a directive with an external template.

### CODE REVIEW

**Comment by yuri** [comment]
I don't think we want to promote the idea of using `console` as a stand-in for `$log`, since this won't work in many cases. Or, at least we need to add a warning about this. The main reason this won't work is that `console` methods depend on context, while `$log` method do not. So, you can do `.then(null, $log.error)`, but not `.then(null, console.error)`.

Second, I think it would be good to do the examples using test style that we end on in the unit testing section (i.e., having a test return a promise rather than calling `done`).

**Comment by SethDavenport** [comment]
OK I'll remove the mocking for $log.

As for the 'done' thing - I don't think I'm using it in this module.  There's only one asynchronous test, and that returns a promise.

**Comment by yuri** [comment]
You are right: this "done" was in my code sample that you _removed_.

**Comment by yuri** [comment]
@SethDavenport Can you rebase and merge?

**Comment by SethDavenport** [comment]
Sure.  The only missing part is the html2js stuff.  I can do that in a separate pass.

**Comment by SethDavenport** [comment]
Done.  Note that it's now section 17 because that seems to be where the placeholder file ended up.

**Pull request merged**
